### ISSUE TITLE
Provide ability to copy examples in documentation without line numbers

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#103]
I really like the embedded examples with tabs for multiple languages (e.g., https://sys-bio.github.io/libOmexMeta/docs-build/composite_annotations/index.html). It would be great to be able to copy out the text without the line numbers. Maybe the package you're using has an option to at least turn the line numbers off.

**Comment by CiaranWelsh** [comment]
Looks like a known bug in the sphinx_rtd_theme - [here](https://github.com/sphinx-doc/sphinx/issues/9363) and [here](https://github.com/readthedocs/sphinx_rtd_theme/issues/1168). It also looks like they have fixed the issue quite recently, though installing the sphinx_rtd_theme from code directly in the master branch did not give me copyable examples. Removing the line numbers for now.
