### ISSUE TITLE
Update example of `to_editor` to current arguments

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#105]
L43 of example in "Simple example of creating a single annotation" section of 
https://sys-bio.github.io/libOmexMeta/docs-build/singular_annotations/index.html
```
editor = rdf.to_editor(sbml, "sbml")
```

**Comment by CiaranWelsh** [comment]
Interesting - this is actually valid syntax since the second argument is a bool and `bool("sbml")` evaluates to True - hence no error when building the docs examples. Thanks for pointing it out.
