### ISSUE TITLE
Some SBML examples have invalid metaids (according to libSBML)

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#106]
Invalid examples:
- [`SimpleRegulation`](https://github.com/sys-bio/libOmexMeta/blob/b1ed1aef1ca30811fb749c45ad3c7366ea681e63/docs/ExampleOutputFiles/create_physical_entity_python.txt)
- [`ToyModel`](https://github.com/sys-bio/libOmexMeta/blob/b1ed1aef1ca30811fb749c45ad3c7366ea681e63/docs/ExampleOutputFiles/create_single_annotation_with_metaids_python.txt)
- [`SmadNuclearTransport`](https://github.com/sys-bio/libOmexMeta/blob/b1ed1aef1ca30811fb749c45ad3c7366ea681e63/tests/python/tests.py)

Example error from libSBML
```
The syntax of 'metaid' attribute values must conform to the syntax of the XML type 'ID'.
Reference: L3V1 Sections 3.2.1 and 3.1.6
 The metaid '#OmexMetaId0000' does not conform to the syntax.
```

**Comment by CiaranWelsh** [comment]
This issue has been resolved  - [see](https://github.com/sys-bio/libOmexMeta/issues/107#issuecomment-891081061)
