### ISSUE TITLE
Automate testing of examples to avoid accumulating broken examples

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#108]
Given issues with the examples such as reported in #107, it would be helpful to add tests for the examples to avoid accumulating broken examples.

**Comment by CiaranWelsh** [comment]
The examples are already valid Python, C or C++ programs that are all executed prior to building the documentation. The source code for the programs themselves are used as each example and the output of each program is collected and used as the output that you see in the documentation. 

See [run_docs_examples](https://github.com/sys-bio/libOmexMeta/blob/master/docs/run_docs_examples.py). 

#107 must have a related but different issue - I'll get there in time.
