### ISSUE TITLE
Turn Logger into a container for storing issues that can be returned to user

### ISSUE THREAD

**Issue by CiaranWelsh** [sys-bio/libOmexMeta#130]
An API that makes it easy to get a list of issues, the level of each issue, and the message associated with each issue would be helpful. This would avoid the need to setup a log file and then parse the log file for errors. I don't have a strong opinion about exactly what this needs to look like.

Methods such as these would be fine:
- log.get_num_issues()
- log.get_issue_level(i_message)
- log.get_issue_message(i_message)

Here's one example from libCellML: https://libcellml.org/documentation/api/v0.2.0/classlibcellml_1_1Logger.
Another is libSBML: http://sbml.org/Software/libSBML/5.18.0/docs/python-api/classlibsbml_1_1_s_b_m_l_error_log.html.

_Originally posted by @jonrkarr in https://github.com/sys-bio/libOmexMeta/issues/102#issuecomment-903028528_

**Comment by CiaranWelsh** [comment]
Implemented in `v1.2.13`. [See docs](https://sys-bio.github.io/libOmexMeta/docs-build/errors_and_logging/errors_and_logging.html#id1).

**Comment by jonrkarr** [comment]
This will be very helpful.
