### ISSUE TITLE
No support for MacOS 10.14

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/libOmexMeta#137]
Same issue here as with https://github.com/sys-bio/roadrunner/issues/879.
Unfortunately, the student from India does not have access to newer Software at the moment.

**Comment by luciansmith** [comment]
At this point, there's no machine I have access to with 10.14; 10.15 is as early as the VMs go.

Does the student still need the earlier version?

**Comment by matthiaskoenig** [comment]
No project is over. We went without libomex for the project. Can be closed.
