### ISSUE TITLE
Add support for python 3.10

### ISSUE THREAD

**Issue by bilalshaikh42** [sys-bio/libOmexMeta#140]
Currently, pip fails to find a compatible version on Python 3.10

**Comment by bilalshaikh42** [comment]
Related: https://github.com/sys-bio/roadrunner/issues/879

**Comment by matthiaskoenig** [comment]
Yes, please add support for python 3.10. I have to drop the `biosimulators-utils` at this point which depend on pyomexmeta.

**Comment by luciansmith** [comment]
Done!

**Comment by matthiaskoenig** [comment]
This is great. Same for the py3.11. Thanks.
