### ISSUE TITLE
Add helper method to display rdf graph to screen

### ISSUE THREAD

**Issue by hsauro** [sys-bio/libOmexMeta#40]
It would be useful to add a helper method to display the rdf graph for platforms such as jupyter, spider, pycharm etc. 

eg

rdf_graph.display()

I used this code which no doubt can be simplified and just rewritten, it just shows that it i possible to do:

   dotstr = rdf_graph.to_string ('dot')
   te.saveToFile ('dot.txt', dotstr)

   (graph,) = pydot.graph_from_dot_file('dot.txt')
   graph.write_png('dot.png')

   import matplotlib.pyplot as plt
   import matplotlib.image as mpimg

   img = mpimg.imread('dot.png')
   plt.imshow(img)
   plt.show()

**Comment by CiaranWelsh** [comment]
Closing in favour of #41
