### ISSUE TITLE
An an option to the library to allow a user to strip out all annotations from an SBML file. 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/libOmexMeta#74]
Request from user:

Add an option to libomexmeta to completely strip out all annotations (except for the metaids) from an SBML model.

Reason: Large models that contain annotations can take a long time to load into simulators, stripping out the verbose annotation text can greatly reduce the size of the SBMl file and permit much faster loading

**Comment by CiaranWelsh** [comment]
Should be easy enough to add a convenience function / static method somewhere.

**Comment by CiaranWelsh** [comment]
Implemented in https://github.com/sys-bio/libOmexMeta/commit/3f3b18e6ced17c5a075235e118fd219306b14eab

Docs here: https://sys-bio.github.io/libOmexMeta/docs-build/stripping_annotations/index.html

Make sure you're using pyomexmeta v1.2.8
