### ISSUE TITLE
Examples indicate extra namespaces

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#84]
I believe the examples e.g., below
```
add_curator("orcid:0000-0001-8254-4958")
add_taxon("taxon/9895")
add_pubmed("pubmed/12334")
```

should not have namespaces in the values and should look like this
```
add_curator("0000-0001-8254-4958")
add_taxon("9895")
add_pubmed("2334")
```

**Comment by CiaranWelsh** [comment]
Fixed in 43e0448dec65c4ade9f31c7b7e40c636b44c5582. The only place I could find the old input style was in the supplementary content demo.
