### ISSUE TITLE
IMPORTANT: Provide way to get errors and warnings from parsing RDF files

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#87]
`pyomexmeta.RDF.from_file` prints errors and warnings to stdout. To embed pyomexmeta into other programs, it would be helpful to be able to retrieve this in a structured way without having to capture and parse the stdout.

**Comment by CiaranWelsh** [comment]
This behaviour actually comes from the redland libraries, the dependency libOmexMeta uses for creating and handling the RDF graphs. I suspect that changing this behaviour is possible but difficult since we'll have modify our copy of the dependency libraries. That is unless I've missed something obvious.

**Comment by jonrkarr** [comment]
The ability to programmatically detect whether a document was successfully parsed seems essential to me. I captured the stdout to figure this out, but this would probably be a roadblock for others. This also won't work on Windows.

I see there are methods in libRDF and raptor to set log handlers. It seems to me that this can be used to capture warnings and errors so that its not necessary to collect stdout or bypass libomexmeta and work with librdf/raptor directly.

`librdf_parser_set_error`
https://librdf.org/docs/api/parser.html

`raptor_world_set_log_handler`
https://librdf.org/raptor/api/tutorial-parser-set-error-warning-handlers.html

**Comment by CiaranWelsh** [comment]
I agree, these functions look promising. I'll look into it.

**Comment by matthiaskoenig** [comment]
+1 for this functionality.

**Comment by CiaranWelsh** [comment]
Implemented in 28528c8637969b77738dbe93f42c92c4d90833e3. See [docs](https://sys-bio.github.io/libOmexMeta/docs-build/errors_and_logging/errors_and_logging.html). Please reopen if something isn't working correctly.

**Comment by jonrkarr** [comment]
I tried the example in the "Switching to the file logger" section. Nothing is saved to the log file.
