### ISSUE TITLE
Provide option to get `pyomexmeta.RDF.query` as a Python object

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#91]
Python `pyomexmeta.RDF.query` returns data in several serialized formats. I see the C version has another option (`queryResultsAsMap`) to get the results as C data structure. Something similar would be helpful for Python.

**Comment by CiaranWelsh** [comment]
This one was a little awkward but should be resolved by 28528c8637969b77738dbe93f42c92c4d90833e3. [Docs here](https://sys-bio.github.io/libOmexMeta/docs-build/querying_rdf/querying_rdf.html#results-as-a-map-dict).

**Comment by jonrkarr** [comment]
In order to use this, it would helpful to also get information about the type (Literal, URI, BNode) of each object. This is encoded into the string return, but not the object return.
