### ISSUE TITLE
Queries on invalid imported files generate segmentation faults

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#92]
Currently, its hard to detect whether a file was parsed correct or not.

When files are invalid, queries on the returned RDF object generate segmentation faults:
```python
import pyomexmeta
rdf = pyomexmeta.RDF.from_file('does-not-exist')
rdf.query("SELECT ?subject ?predicate ?object WHERE { ?subject ?predicate ?object }", 'json')
```

Environment:
- pyomexmeta: 1.2.10
- python: 3.9
- Ubuntu

**Comment by CiaranWelsh** [comment]
Fixed in v1.2.12. Python doesn't crash but an error message is passed through the logger.
