### ISSUE TITLE
Provide error messages for invalid XML content

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#95]
Although pyomexmeta considers the following XML invalid, not error message or exception is provided. Some information about the errors would be helpful.

```python
from pyomexmeta import RDF
rdf = RDF()
editor = rdf.to_editor('<sbml></sbml>')
```

**Comment by CiaranWelsh** [comment]
The issue here is validating sbml - which is completely possible using `libsbml`. However, we decided not to depend on libsbml in attempts to make libOmexMeta more generally applicable to models encoded in other languages (i.e. cellml, maybe others in future). So now this question becomes: how can we validate the accuracy of user input without libsbml? By extension, how can we validate accuracy of other markup languages?

**Comment by jonrkarr** [comment]
My concern is simpler. If libOmexMeta considers `<sbml></sbml>` to be invalid (evidenced by segmentation fault), I think it's important to either (a) communicate some other validation program that users can run to get informative error messages or (b) libOmexMeta provides such informative messages. The latter would be more convenient. Its also unclear to me that any other program would be sufficient, given the unique focus of this library on annotations in model files.

It sounds like libSBML might be helpful, and libOmexMeta requires SBML-specific code anyway. As I understand, the input to semantic extraction to libOmexMeta is not arbitrary XML, but XML in specific schemas. Specifically, the path forward to support additional model languages is to write additional semantic extractors similar to `SBMLSemanticExtraction`. Given that separate code (plugins?) is needed to handle each model language, it seems easiest to me to implement that using libraries such as libSBML and libCellML where possible.

If the goal is to validate the accuracy of models in other languages, I think this has to rely on libraries for those languages. We've been collating such validation in BioSimulators as a part of validating simulations (involving various model languages). Unfortunately, I've only found a few languages with good validation tools. As a result, I don't think there's many other model language libraries that libOmexMeta could leverage. For most languages, libOmexMeta probably has to assume that models are valid and focus on validating the RDF that it produces rather than on input in various languages.
- SBML: libSBML is the gold standard for model validation, but it doesn't validate the content of annotations. Either libOmexMeta could fill this role, or libSBML could potentially do this.
- CellML: It looks like the new libCellML will be good for CellML 2.0. The schema is good for CellML 1.0.
- NeuroML/LEMS: They're tools provide incomplete validation. Written in Java, with a wrapper for Python.
- BioNetGen: They're creating a library, but their XML format (which could capture annotations) is less commonly used. Thus, the utility to libOmexMeta would be limited. Written in Python.
- Smoldyn: Format doesn't capture annotations. There is a library, but its purpose is somewhat different.

**Comment by CiaranWelsh** [comment]
>For most languages, libOmexMeta probably has to assume that models are valid and focus on >validating the RDF that it produces rather than on input in various languages.

I think this is the right solution here. Adding individual support for model languages is impractical to maintain/extend and a plugin architecture is technically challenging, particularly to add in after the software has already been designed/implemented.

The latest release (v1.2.12) no longer segfaults with the code.
